openapi: 3.0.0
info:
  description: GraphSense API
  title: GraphSense API
  version: 0.4.4
servers:
- url: http://openapi_server:9000
paths:
  /stats:
    get:
      operationId: get_statistics
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stats'
          description: OK
      summary: Get statistics of supported currencies
      tags:
      - general
      x-openapi-router-controller: openapi_server.controllers.general_controller
  /{currency}/addresses/{address}:
    get:
      operationId: get_address_with_tags
      parameters:
      - description: The cryptocurrency (e.g., btc)
        example: btc
        explode: false
        in: path
        name: currency
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: The cryptocurrency address
        example: 3Hrnn1UN78uXgLNvtqVXMjHwB41PmX66X4
        explode: false
        in: path
        name: address
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/address'
          description: OK
      summary: Get an address with tags
      tags:
      - addresses
      x-openapi-router-controller: openapi_server.controllers.addresses_controller
  /{currency}/blocks:
    get:
      operationId: list_blocks
      parameters:
      - description: The cryptocurrency (e.g., btc)
        example: btc
        explode: false
        in: path
        name: currency
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: Resumption token for retrieving the next page
        example: 0400030bff00f07fffff9b00
        explode: true
        in: query
        name: page
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blocks'
          description: OK
      summary: Get all blocks
      tags:
      - blocks
      x-openapi-router-controller: openapi_server.controllers.blocks_controller
  /{currency}/blocks/{height}:
    get:
      operationId: get_block
      parameters:
      - description: The cryptocurrency (e.g., btc)
        example: btc
        explode: false
        in: path
        name: currency
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: The block height
        example: 1
        explode: false
        in: path
        name: height
        required: true
        schema:
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/block'
          description: OK
      summary: Get a block by its height
      tags:
      - blocks
      x-openapi-router-controller: openapi_server.controllers.blocks_controller
  /{currency}/blocks/{height}/txs:
    get:
      operationId: list_block_txs
      parameters:
      - description: The cryptocurrency (e.g., btc)
        example: btc
        explode: false
        in: path
        name: currency
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: The block height
        example: 1
        explode: false
        in: path
        name: height
        required: true
        schema:
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/block_txs'
          description: OK
      summary: Get all blocks (100 per page)
      tags:
      - blocks
      x-openapi-router-controller: openapi_server.controllers.blocks_controller
  /{currency}/blocks/{height}/txs.csv:
    get:
      operationId: list_block_txs_csv
      parameters:
      - description: The cryptocurrency (e.g., btc)
        example: btc
        explode: false
        in: path
        name: currency
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: The block height
        example: 1
        explode: false
        in: path
        name: height
        required: true
        schema:
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            text/csv:
              schema:
                items:
                  $ref: '#/components/schemas/block_tx_summary'
                type: array
          description: OK
      summary: Get all blocks as CSV
      tags:
      - blocks
      x-openapi-router-controller: openapi_server.controllers.blocks_controller
components:
  parameters:
    currency:
      description: The cryptocurrency (e.g., btc)
      example: btc
      explode: false
      in: path
      name: currency
      required: true
      schema:
        format: string
        type: string
      style: simple
    height:
      description: The block height
      example: 1
      explode: false
      in: path
      name: height
      required: true
      schema:
        minimum: 1
        type: integer
      style: simple
    page:
      description: Resumption token for retrieving the next page
      example: 0400030bff00f07fffff9b00
      explode: true
      in: query
      name: page
      required: false
      schema:
        type: string
      style: form
    address:
      description: The cryptocurrency address
      example: 3Hrnn1UN78uXgLNvtqVXMjHwB41PmX66X4
      explode: false
      in: path
      name: address
      required: true
      schema:
        format: string
        type: string
      style: simple
  schemas:
    stats:
      example:
        currencies:
        - no_addresses: 1
          no_labels: 2
          name: name
          no_entities: 5
          no_address_relations: 6
          no_blocks: 0
          no_txs: 5
          timestamp: 7
        - no_addresses: 1
          no_labels: 2
          name: name
          no_entities: 5
          no_address_relations: 6
          no_blocks: 0
          no_txs: 5
          timestamp: 7
      properties:
        currencies:
          items:
            $ref: '#/components/schemas/currency_stats'
          type: array
      type: object
    currency_stats:
      example:
        no_addresses: 1
        no_labels: 2
        name: name
        no_entities: 5
        no_address_relations: 6
        no_blocks: 0
        no_txs: 5
        timestamp: 7
      properties:
        name:
          type: string
        no_blocks:
          format: int64
          type: integer
        no_address_relations:
          format: int64
          type: integer
        no_addresses:
          format: int64
          type: integer
        no_entities:
          format: int64
          type: integer
        no_txs:
          format: int64
          type: integer
        no_labels:
          format: int64
          type: integer
        timestamp:
          format: int64
          type: integer
      title: statistics of a cryptocurrency
      type: object
    block:
      example:
        block_hash: block_hash
        height: 1
        no_txs: 6
        timestamp: 1
      properties:
        block_hash:
          format: string
          type: string
        height:
          format: int64
          minimum: 1
          type: integer
        no_txs:
          format: int64
          type: integer
        timestamp:
          format: int64
          type: integer
      type: object
    block_txs:
      example:
        txs:
        - total_output:
            eur: 0
            usd: 6
            value: 1
          no_outputs: 1
          total_input:
            eur: 0
            usd: 6
            value: 1
          tx_hash: tx_hash
          no_inputs: 6
        - total_output:
            eur: 0
            usd: 6
            value: 1
          no_outputs: 1
          total_input:
            eur: 0
            usd: 6
            value: 1
          tx_hash: tx_hash
          no_inputs: 6
        height: 0
      properties:
        height:
          type: integer
        txs:
          items:
            $ref: '#/components/schemas/block_tx_summary'
          type: array
      type: object
    block_tx_summary:
      example:
        total_output:
          eur: 0
          usd: 6
          value: 1
        no_outputs: 1
        total_input:
          eur: 0
          usd: 6
          value: 1
        tx_hash: tx_hash
        no_inputs: 6
      properties:
        tx_hash:
          type: string
        no_inputs:
          format: int64
          type: integer
        no_outputs:
          format: int64
          type: integer
        total_input:
          $ref: '#/components/schemas/values'
        total_output:
          $ref: '#/components/schemas/values'
      type: object
    blocks:
      example:
        next_page: next_page
        blocks:
        - block_hash: block_hash
          height: 1
          no_txs: 6
          timestamp: 1
        - block_hash: block_hash
          height: 1
          no_txs: 6
          timestamp: 1
      properties:
        next_page:
          format: string
          type: string
        blocks:
          items:
            $ref: '#/components/schemas/block'
          type: array
      type: object
    address:
      example:
        total_spent:
          eur: 0
          usd: 6
          value: 1
        in_degree: 2
        address: address
        balance:
          eur: 0
          usd: 6
          value: 1
        no_incoming_txs: 9
        out_degree: 7
        no_outgoing_txs: 3
        first_tx:
          tx_hash: tx_hash
          height: 5
          timestamp: 5
        last_tx:
          tx_hash: tx_hash
          height: 5
          timestamp: 5
        total_received:
          eur: 0
          usd: 6
          value: 1
        tags:
        - label: label
        - label: label
      properties:
        address:
          description: Address
          type: string
        balance:
          $ref: '#/components/schemas/values'
        first_tx:
          $ref: '#/components/schemas/tx_summary'
        last_tx:
          $ref: '#/components/schemas/tx_summary'
        in_degree:
          format: int64
          type: integer
        out_degree:
          format: int64
          type: integer
        no_incoming_txs:
          format: int64
          type: integer
        no_outgoing_txs:
          format: int64
          type: integer
        total_received:
          $ref: '#/components/schemas/values'
        total_spent:
          $ref: '#/components/schemas/values'
        tags:
          description: Tags
          items:
            $ref: '#/components/schemas/tag'
          type: array
      required:
      - address
      - balance
      - first_tx
      - in_degree
      - last_tx
      - no_incoming_txs
      - no_outgoing_txs
      - out_degree
      - total_received
      - total_spent
      type: object
    tx_summary:
      example:
        tx_hash: tx_hash
        height: 5
        timestamp: 5
      properties:
        height:
          description: Transaction height
          format: int64
          type: integer
        timestamp:
          description: Transaction timestamp
          format: int64
          type: integer
        tx_hash:
          description: Transaction hash
          type: string
      required:
      - height
      - timestamp
      - tx_hash
      type: object
    tag:
      example:
        label: label
      properties:
        label:
          type: string
      type: object
    values:
      example:
        eur: 0
        usd: 6
        value: 1
      properties:
        eur:
          format: int64
          type: integer
        usd:
          format: int64
          type: integer
        value:
          format: int64
          type: integer
      type: object
    next_page:
      format: string
      type: string
